services:
  flask_app:
    build:
      context: .  # Build context where your Dockerfile is located
      dockerfile: Dockerfile
    container_name: flask_app
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - ${BASE_PATH}:/usr/src/app/assets
    ports:
      - "5000:5000"
    command: ["gunicorn", "-w", "1", "--reload", "-b", "0.0.0.0:5000", "--timeout", "1200", "app:app"]
 